export { COMPONENT_DEFS, COMMON_PROPS, DEFAULT_EVENT } from './components/index.js'

export const PALETTE_CATEGORIES = [
  'Standard', 'Additional', 'Win32', 'System', 'Dialogs',
  'Data Access', 'Data Controls', 'dbExpress', 'LiveBindings',
  'Internet', 'Indy Clients', 'Indy Servers', 'Samples',
]

export const EVENT_LIST = [
  'OnClick', 'OnChange', 'OnEnter', 'OnExit',
  'OnKeyDown', 'OnKeyPress', 'OnKeyUp',
  'OnMouseDown', 'OnMouseMove', 'OnMouseUp', 'OnDblClick',
]

export const FORM_EVENTS = ['OnCreate', 'OnDestroy', 'OnShow', 'OnClose', 'OnResize']

export const MENU_DEFS = {
  File: [
    'New ▶',
    'Open...',
    'Open Project... | Ctrl+F11',
    'Open From Version Control...',
    'Open Recent ▶',
    'Open Favorite ▶',
    '-',
    'Save | Ctrl+S',
    'Save As...',
    'Save Project As...',
    'Save All | Ctrl+Shift+S',
    '-',
    'Close',
    'Close All',
    '-',
    'Use Unit... | Alt+F11',
    'Print...',
    '-',
    'Exit',
  ],
  Edit: [
    'Undo | Ctrl+Z',
    'Redo | Ctrl+Shift+Z',
    '-',
    'Cut | Ctrl+X',
    'Copy | Ctrl+C',
    'Paste | Ctrl+V',
    'MultiPaste',
    'Delete | Ctrl+Del',
    'Select All | Ctrl+A',
    '-',
    'Compare ▶',
    '-',
    'Align to Grid',
    'Bring to Front',
    'Send to Back',
    'Show Non-Visual Components | Ctrl+H',
  ],
  Search: [
    'Find... | Ctrl+F',
    'Find in Files... | Ctrl+Shift+F',
    'Replace... | Ctrl+R',
    'Search Again | F3',
    'Incremental Search | Ctrl+E',
    'IDE Insight... | Ctrl+.',
    '-',
    'Go to Definition',
    'Go to Implementation',
    '-',
    'Go to Line Number... | Alt+G',
    'Go to Address',
  ],
  View: [
    'Debug Windows ▶',
    'Tool Windows ▶',
    'Desktops ▶',
    'Toolbars ▶',
    '-',
    'Units... | Ctrl+F12',
    'Forms... | Shift+F12',
    'Show Code/Designer | F12',
    'New Edit Window',
    'History ▶',
    'Editor ▶',
    '-',
    'Type Library',
    'Registered Type Libraries',
    '-',
    'Welcome Page',
    'Configuration Manager',
    '-',
    'Broadcast to devices',
  ],
  Refactor: [
    'Rename...',
    'Extract Method...',
    'Extract Resource String...',
    'Find Unit...',
    '-',
    'Find References...',
  ],
  Project: [
    'Add to Project... | Shift+F11',
    'Remove from Project...',
    'Add to Repository...',
    'View Source',
    'Format Project Sources...',
    '-',
    'Add New Project...',
    'Add Existing Project...',
    '-',
    'Compile | Ctrl+F9',
    'Build | Shift+F9',
    'Deploy | Ctrl+Alt+Shift+F9',
    'Information for Project',
    'Method Toxicity Metrics...',
    '-',
    'Compile All Projects',
    'Build All Projects',
    '-',
    'Dependencies...',
    'Project Page Options...',
    'Options... | Ctrl+Shift+F11',
  ],
  Run: [
    'Run | F9',
    'Run Without Debugging | Ctrl+Shift+F9',
    'Parameters...',
    'ActiveX Server ▶',
    'Load Process...',
    'Attach to Process...',
    '-',
    'Step Over | F8',
    'Trace Into | F7',
    'Trace to Next Source Line | Shift+F7',
    'Run to Cursor | F4',
    'Run Until Return | Shift+F8',
    'Show Execution Point',
    'Program Pause',
    'Program Reset | Ctrl+F2',
    '-',
    'Inspect...',
    'Evaluate/Modify... | Ctrl+F7',
    'Add Watch... | Ctrl+F5',
    'Add Breakpoint ▶',
  ],
  Component: [
    'New Component...',
    'Install Component...',
    'Create Component Template...',
    '-',
    'Install Packages...',
    'Import Component...',
    'Import WSDL...',
  ],
  Tools: [
    'Options...',
    'Template Libraries...',
    'Reload LSP Server',
    'GetIt Package Manager...',
    'Manage Features...',
    'Build Tools...',
    'Configure Tools...',
    '-',
    'Bitmap Style Designer',
    'FireDAC Explorer',
    'FireDAC Monitor',
    'REST Debugger',
    'RAD Server Console',
  ],
  Tabs: [
    'Next Tab | Ctrl+Tab',
    'Previous Tab | Ctrl+Shift+Tab',
    '-',
    'Welcome Page',
    '-',
    '(no windows)',
  ],
  Help: [
    'RAD Studio Help ▶',
    'RAD Studio Docwiki',
    'Third-Party Help',
    'Platforms SDK Help ▶',
    'Help Wizards ▶',
    '-',
    'Embarcadero Home Page',
    'Embarcadero Developer Support Page',
    'Embarcadero Community Site',
    'Delphi Home Page',
    'Embarcadero Blogs',
    '-',
    'License Manager...',
    'Welcome Configuration',
    '-',
    'About Embarcadero® Delphi',
  ],
}

// Items greyed out when no form/project tab is open
export const MENU_DISABLED_NO_PROJECT = {
  File:     new Set(['Save', 'Save As...', 'Save Project As...', 'Save All', 'Close', 'Close All', 'Use Unit...', 'Print...']),
  Edit:     new Set(['Undo', 'Redo', 'Cut', 'Copy', 'Paste', 'MultiPaste', 'Delete', 'Select All', 'Compare', 'Align to Grid', 'Bring to Front', 'Send to Back', 'Show Non-Visual Components']),
  Search:   new Set(['Find...', 'Find in Files...', 'Replace...', 'Search Again', 'Incremental Search', 'Go to Definition', 'Go to Implementation', 'Go to Line Number...', 'Go to Address']),
  View:     new Set(['Units...', 'Forms...', 'Show Code/Designer', 'New Edit Window', 'History', 'Editor', 'Type Library', 'Registered Type Libraries', 'Broadcast to devices']),
  Refactor: new Set(['Rename...', 'Extract Method...', 'Extract Resource String...', 'Find Unit...', 'Find References...']),
  Project:  new Set(['Add to Project...', 'Remove from Project...', 'Add to Repository...', 'View Source', 'Format Project Sources...', 'Compile', 'Build', 'Deploy', 'Information for Project', 'Method Toxicity Metrics...', 'Compile All Projects', 'Build All Projects', 'Dependencies...', 'Project Page Options...', 'Options...']),
  Run:      new Set(['Run', 'Run Without Debugging', 'Parameters...', 'ActiveX Server', 'Load Process...', 'Attach to Process...', 'Step Over', 'Trace Into', 'Trace to Next Source Line', 'Run to Cursor', 'Run Until Return', 'Show Execution Point', 'Program Pause', 'Program Reset', 'Inspect...', 'Evaluate/Modify...', 'Add Watch...', 'Add Breakpoint']),
  Component:new Set(['Create Component Template...']),
  Tabs:     new Set(['Next Tab', 'Previous Tab']),
  Help:     new Set(['Third-Party Help']),
}

export const PLATFORMS = ['Windows 64-bit','Windows 32-bit','Linux 64-bit','macOS ARM 64-bit','Android 64-bit','iOS Device 64-bit']
export const CONFIGURATIONS = ['Debug', 'Release']
export const LAYOUTS = ['Default Layout', 'Classic Undocked', 'Debug', 'Designer', 'Editor only']

export const DELPHI_COLORS = {
  clBtnFace: '#f0f0f0', clWindow: '#ffffff', clWhite: '#ffffff', clBlack: '#000000',
  clRed: '#ff0000', clBlue: '#0000ff', clGreen: '#008000', clYellow: '#ffff00',
  clNavy: '#000080', clMaroon: '#800000', clSilver: '#c0c0c0', clGray: '#808080',
  clTeal: '#008080', clActiveCaption: '#99b4d1',
}
